kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: amd-dev
 name:  role-azure-devops-amd
rules:
 - apiGroups: ["*"]
   resources: ["*"]
   verbs: ["*"]
---
apiVersion: v1
kind: Secret
metadata:
  namespace: amd-dev
  name: secret-azure-devops-amd
  annotations: 
    kubernetes.io/service-account.name: sa-azure-devops-amd
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: amd-dev
  name: sa-azure-devops-amd
secrets:
- name: secret-azure-devops-amd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: amd-dev
  name: rolebinding-azure-devops-amd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-azure-devops-amd
subjects:
- kind: ServiceAccount
  name: sa-azure-devops-amd